#!/usr/bin/env python

"""
Project Euler
Ed Salisbury <ed.salisbury+git@gmail.com>
GitHub: https://github.com/EdSalisbury
Written: 2014/01/22
Last Modified: 2024/01/25

Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def main(max_num):
    num1 = 1
    num2 = 2
    sum = 0

    while num1 < max_num:
        if num1 % 2 == 0:
            sum += num1
    
        fib = num1 + num2
        num1 = num2
        num2 = fib

    return(sum)

if __name__ == "__main__":
    sum = main(4000000)
    print (f"The sum of the even-valued terms is: {sum}")
